spring:
  application:
    name: shodh-a-code
  datasource:
    url: jdbc:h2:mem:shodhdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.shodhai: INFO

server:
  port: 8080

judge:
  docker:
    image: shodh-judge:latest
    memory: 256m
    cpus: 0.5
    timeout: 10
